# Copyright 2020 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: rscohn2/oneapi-spec:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install prerequisites
      run: |
          apt-get update -qq
          DEBIAN_FRONTEND=noninteractive xargs -a packages.txt apt-get install -qq
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade --quiet -r requirements.txt
    - name: Build doc
      run: |
          . venv/bin/activate
          python doc.py html
          python doc.py latexpdf
          python doc.py spelling
          # ignore non-zero error code
          reuse lint > build/reuse.txt || true
    - name: Archive build directory
      uses: actions/upload-artifact@v1
      with:
          name: build
          path: build
    - name: Checkout gh-pages
      if: ${{ github.ref == 'refs/heads/dpcpp' }}
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages
    - name: Publish to github pages
      if: ${{ github.ref == 'refs/heads/dpcpp' }}
      run: |
          cd gh-pages
	  rm -rf *
          cp -r ../build/html/* .
          cp ../build/latex/*.pdf .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update from github actions"
          git push
